//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class finsupportsall
    {
        public int id { get; set; }
        public Nullable<decimal> fo2019 { get; set; }
        public Nullable<decimal> fo2020 { get; set; }
        public Nullable<decimal> fo2021 { get; set; }
        public Nullable<decimal> fo2022 { get; set; }
        public Nullable<decimal> fo2023 { get; set; }
        public Nullable<decimal> fo2024 { get; set; }
        public string finsource { get; set; }
        public Nullable<decimal> fo_total { get; set; }
        public string finsourcecode { get; set; }
        public Nullable<long> metaid_rp { get; set; }
    
        public virtual RegProjectTable RegProjectTable { get; set; }
    }
}
