//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegProjectEntities : DbContext
    {
        public RegProjectEntities()
            : base("name=RegProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<finsupportsall> finsupportsall { get; set; }
        public virtual DbSet<participants> participants { get; set; }
        public virtual DbSet<purposemonthdistribution> purposemonthdistribution { get; set; }
        public virtual DbSet<purposes> purposes { get; set; }
        public virtual DbSet<RegProjectTable> RegProjectTable { get; set; }
        public virtual DbSet<results> results { get; set; }
        public virtual DbSet<roiv> roiv { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<subject> subject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tasks> tasks { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
