//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class participants
    {
        public long metaid { get; set; }
        public Nullable<long> recordid { get; set; }
        public string fio { get; set; }
        public string headpost { get; set; }
        public string immsupervisor { get; set; }
        public Nullable<int> percemploy { get; set; }
        public string roleinproj { get; set; }
        public string codereestr { get; set; }
        public Nullable<long> metaid_rp { get; set; }
    
        public virtual RegProjectTable RegProjectTable { get; set; }
    }
}
