//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class purposes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purposes()
        {
            this.purposemonthdistribution1 = new HashSet<purposemonthdistribution>();
        }
    
        public long metaid { get; set; }
        public Nullable<long> recordid { get; set; }
        public string mrkname { get; set; }
        public Nullable<int> code { get; set; }
        public string description { get; set; }
        public string typemrk { get; set; }
        public string typevaluemrk { get; set; }
        public Nullable<int> okeicode { get; set; }
        public string okeiname { get; set; }
        public Nullable<decimal> basicvalueind { get; set; }
        public Nullable<decimal> value2018 { get; set; }
        public Nullable<decimal> value2019 { get; set; }
        public Nullable<decimal> value2020 { get; set; }
        public Nullable<decimal> value2021 { get; set; }
        public Nullable<decimal> value2022 { get; set; }
        public Nullable<decimal> value2023 { get; set; }
        public Nullable<decimal> value2024 { get; set; }
        public Nullable<decimal> value2025 { get; set; }
        public Nullable<decimal> value2026 { get; set; }
        public Nullable<decimal> value2027 { get; set; }
        public Nullable<decimal> value2028 { get; set; }
        public Nullable<decimal> value2029 { get; set; }
        public Nullable<decimal> value2030 { get; set; }
        public string dockind { get; set; }
        public string approgv { get; set; }
        public string approvtdatenpa { get; set; }
        public string numbernpa { get; set; }
        public string namenpa { get; set; }
        public string sourcedata { get; set; }
        public string fpmrkid { get; set; }
        public string fpmrkname { get; set; }
        public Nullable<long> tasksrecordid { get; set; }
        public Nullable<int> taskcode { get; set; }
        public string taskname { get; set; }
        public string taskrespexec { get; set; }
        public string targettype { get; set; }
        public string ozrname { get; set; }
        public string ozrnum { get; set; }
        public string ozrbeneficiar { get; set; }
        public string ozrokeicode { get; set; }
        public string ozrokeiname { get; set; }
        public string ozrtype { get; set; }
        public Nullable<int> yearend { get; set; }
        public Nullable<int> establishact { get; set; }
        public Nullable<int> lvlmrk { get; set; }
        public Nullable<int> purposemonthdistribution { get; set; }
        public Nullable<long> metaid_rp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purposemonthdistribution> purposemonthdistribution1 { get; set; }
        public virtual RegProjectTable RegProjectTable { get; set; }
    }
}
