//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class purposemonthdistribution
    {
        public short year { get; set; }
        public Nullable<decimal> mrk02 { get; set; }
        public Nullable<decimal> mrk03 { get; set; }
        public Nullable<decimal> mrk04 { get; set; }
        public Nullable<decimal> mrk05 { get; set; }
        public Nullable<decimal> mrk06 { get; set; }
        public Nullable<decimal> mrk07 { get; set; }
        public Nullable<decimal> mrk08 { get; set; }
        public Nullable<decimal> mrk09 { get; set; }
        public Nullable<decimal> mrk10 { get; set; }
        public Nullable<decimal> mrk11 { get; set; }
        public Nullable<decimal> mrk12 { get; set; }
        public Nullable<decimal> mrkendyaer { get; set; }
        public Nullable<int> after0112 { get; set; }
        public string reasonsmo { get; set; }
        public long recordid { get; set; }
        public Nullable<long> metaid_purposes { get; set; }
    
        public virtual purposes purposes { get; set; }
    }
}
