//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegProjectTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegProjectTable()
        {
            this.finsupportsall1 = new HashSet<finsupportsall>();
            this.participants1 = new HashSet<participants>();
            this.purposes1 = new HashSet<purposes>();
            this.tasks1 = new HashSet<tasks>();
        }
    
        public long metaid { get; set; }
        public long recordid { get; set; }
        public string code { get; set; }
        public string fullname { get; set; }
        public string shortname { get; set; }
        public Nullable<short> idfp { get; set; }
        public string fpcode { get; set; }
        public string fpname { get; set; }
        public string curator { get; set; }
        public string person { get; set; }
        public string kvsr { get; set; }
        public string actualversion { get; set; }
        public Nullable<int> subject { get; set; }
        public Nullable<long> roiv { get; set; }
        public Nullable<int> purposes { get; set; }
        public Nullable<int> tasks { get; set; }
        public Nullable<int> participants { get; set; }
        public Nullable<int> finsupportsall { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<finsupportsall> finsupportsall1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participants> participants1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purposes> purposes1 { get; set; }
        public virtual subject subject1 { get; set; }
        public virtual roiv roiv1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tasks> tasks1 { get; set; }
    }
}
