//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tasks()
        {
            this.results = new HashSet<results>();
        }
    
        public long metaid { get; set; }
        public Nullable<long> recordid { get; set; }
        public string name { get; set; }
        public Nullable<int> code { get; set; }
        public string nprecordid { get; set; }
        public string targettype { get; set; }
        public string ozrrecordid { get; set; }
        public string ozrname { get; set; }
        public string ozrnum { get; set; }
        public string ozrbeneficiar { get; set; }
        public string ozrokeicode { get; set; }
        public string ozrokeiname { get; set; }
        public string ozrtype { get; set; }
        public Nullable<long> result { get; set; }
        public Nullable<long> metaid_rp { get; set; }
    
        public virtual RegProjectTable RegProjectTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<results> results { get; set; }
    }
}
